(function(){
'use strict';
if(!STORE_NAMES.includes('syncConflicts'))STORE_NAMES.push('syncConflicts');

const ADV_SOURCES=[
{id:'tx-bdo-bead',title:'Texas BEAD Program — Final Proposal',agency:'Texas Broadband Development Office / Texas Comptroller',jurisdiction:'Texas',date:'Final Proposal approved 2025-12-04; accessed 2026-09-28',grade:'A',freshness:'Recent',url:'https://comptroller.texas.gov/programs/broadband/funding/bead/',tags:['broadband','BEAD','telehealth','community anchor institutions','rural'],note:'Texas reports 22 selected applicants, more than 240,000 broadband-serviceable locations and more than 2,700 community anchor institutions, with $1.2B federal grant funds and $177M state match in the approved Final Proposal.'},
{id:'hhsc-rural-peds-teleconnect',title:'SFY 2026 Pediatric Tele-Connectivity Resource Program for Rural Texas',agency:'Texas HHSC',jurisdiction:'Texas',date:'RFA released 2026-06-03',grade:'A',freshness:'Recent',url:'https://resources.hhs.texas.gov/rfa/hhs0017228',tags:['rural','telehealth','pediatric','broadband','hospital','clinic'],note:'Grant program designed to connect rural hospitals and rural health clinics with pediatric specialists/subspecialists or eligible higher-education partners in the Texas Child Mental Health Care Consortium.'},
{id:'dshs-chw-current',title:'Texas Community Health Worker / Promotor(a) Program',agency:'Texas DSHS',jurisdiction:'Texas',date:'accessed 2026-09-28',grade:'A',freshness:'Recent',url:'https://www.dshs.texas.gov/community-health-worker',tags:['CHW','promotora','navigation','workforce','community'],note:'Texas DSHS administers CHW training and certification. Paid CHWs require DSHS certification; current pathways include approved training or qualifying experience.'},
{id:'dshs-chw-competencies',title:'Texas CHW Core Competencies',agency:'Texas DSHS',jurisdiction:'Texas',date:'2026 competency transition',grade:'A',freshness:'Recent',url:'https://www.dshs.texas.gov/community-health-worker/chw-core-competencies',tags:['CHW','competencies','navigation','education','research'],note:'Updated Texas CHW competencies took effect February 1, 2026, with training-center curricula required to align by August 1, 2026.'},
{id:'tx-health-data',title:'Texas Health Data',agency:'Texas DSHS',jurisdiction:'Texas',date:'accessed 2026-09-28',grade:'A',freshness:'Live',url:'https://healthdata.dshs.texas.gov/',tags:['maternal','infant','dashboard','public health','data'],note:'Official Texas dashboards include maternal and infant health topics and describe underlying sources and limitations.'},
{id:'hhsc-crisis',title:'Texas Mental Health Crisis Services',agency:'Texas HHSC',jurisdiction:'Texas',date:'accessed 2026-09-28',grade:'A',freshness:'Live',url:'https://hhs.texas.gov/services/mental-health-substance-use/mental-health-crisis-services',tags:['988','crisis','mental health','LMHA','behavioral health'],note:'Texas HHSC lists 988, 2-1-1 and county-serving local mental/behavioral health authority crisis contacts.'},
{id:'trystero-0253',title:'Trystero 0.25.x Documentation and 0.25.3 Release',agency:'Trystero / GitHub',jurisdiction:'Software',date:'0.25.3 released 2026-07-13',grade:'C',freshness:'Recent',url:'https://github.com/dmotz/trystero',tags:['Trystero','WebRTC','Nostr','MQTT','BitTorrent','IPFS','TURN'],note:'Trystero 0.25.x uses object-based actions. The bundle intentionally pins 0.25.3 and supports Nostr, MQTT, BitTorrent and IPFS discovery.'},
{id:'webllm-worker-docs',title:'WebLLM — Using Web Workers',agency:'MLC AI',jurisdiction:'Software',date:'WebLLM docs 0.2.85 accessed 2026-09-28',grade:'C',freshness:'Recent',url:'https://webllm.mlc.ai/docs/user/advanced_usage.html',tags:['WebLLM','WebGPU','worker','local AI','IndexedDB'],note:'WebLLM documents dedicated Web Worker inference through WebWorkerMLCEngineHandler and CreateWebWorkerMLCEngine, with IndexedDB model caching available.'},
{id:'hhsc-services-directory',title:'Texas HHS Service Office Finder',agency:'Texas HHSC',jurisdiction:'Texas',date:'accessed 2026-09-28',grade:'A',freshness:'Live',url:'https://resources.hhs.texas.gov/pages/find-services',tags:['ADRC','AAA','LMHA','LIDDA','aging','disability','behavioral health'],note:'County/ZIP service-office finder for aging, disability, behavioral-health and IDD resources; HHSC also lists 855-937-2372 for help identifying services.'},
{id:'tx-hicap',title:'Texas Medicare Help / HICAP',agency:'Texas HHSC',jurisdiction:'Texas',date:'accessed 2026-09-28',grade:'A',freshness:'Live',url:'https://hhs.texas.gov/services/health/medicare',tags:['Medicare','HICAP','benefits counseling','seniors'],note:'Texas HHSC lists free Medicare benefits counseling through HICAP and the Texas Medicare Help Line at 800-252-9240.'},
{id:'cms-bill-rights',title:'Know Your Medical Bill Rights',agency:'CMS',jurisdiction:'United States',date:'page modified 2026-08-25',grade:'A',freshness:'Recent',url:'https://www.cms.gov/initiatives/your-patient-rights/medical-bill-rights/know-your-medical-bill-rights',tags:['billing','No Surprises Act','good faith estimate','dispute'],note:'CMS explains federal surprise-billing protections and good-faith-estimate dispute pathways, with important exceptions.'},
{id:'hhsc-disability',title:'Texas HHS Disability Services',agency:'Texas HHSC',jurisdiction:'Texas',date:'accessed 2026-09-28',grade:'A',freshness:'Live',url:'https://hhs.texas.gov/services/disability/',tags:['disability','ECI','ADRC','accessibility','Medicaid'],note:'Texas HHS disability-services hub includes benefit pathways, service-office finders and Early Childhood Intervention information.'}
];
for(const s of ADV_SOURCES)if(!SOURCES.some(x=>x.id===s.id))SOURCES.push(s);

const ADV_DISCIPLINES=['Public health','Primary care','Nursing','EMS / emergency management','Behavioral health','Pharmacy','Dental','Maternal / child health','Community health workers','Social work','Disability / accessibility','Transportation','Housing','Food systems','Water / sanitation','Energy / utilities','Schools / education','Broadband / IT','Benefits / finance','Research / data','Nonprofit / faith community','Employers / occupational health','Local government','State / public institution','University / education','Family / caregiver','Business / corporation'];

function tip(id,label,text){return `<span class="tip-wrap"><button type="button" class="tip-btn" aria-label="Explain ${esc(label)}" aria-describedby="tip-${id}" aria-expanded="false">?</button><span class="tip-box" role="tooltip" id="tip-${id}">${text}</span></span>`}
function list(items){return `<ul>${items.map(x=>`<li>${x}</li>`).join('')}</ul>`}

function renderP2PCollab(){return `${renderRouteHeader('Multidisciplinary Peer Collaboration','Local-first workspaces with Trystero 0.25.3 decentralized discovery and direct WebRTC room traffic. Same-device BroadcastChannel remains available without Trystero or network access.')}
<section class="section"><div class="shared-boundary"><strong>Shared-data boundary:</strong> multiplayer workspaces are for projects, tasks, comments, decisions, evidence and non-sensitive community planning. Do not place patient names, diagnoses, medication lists, insurance identifiers, pregnancy/disability details or other protected/sensitive health information in public or peer rooms. Peer IDs, aliases, roles and organization names are self-asserted and <strong>not verified identities</strong>.</div></section>
<section class="section"><h2>Peer network</h2><div class="p2p-status-grid"><div class="p2p-stat"><div class="kicker">Public commons</div><strong id="publicLobbyStatus">Starting…</strong><p class="small muted">Default Nostr-discovered lobby. Presence only; workspace records are not auto-published.</p></div><div class="p2p-stat"><div class="kicker">Workspace room</div><strong id="p2pState">Not joined</strong><p id="p2pMessage" class="small muted">Same-device fallback is available after joining a room.</p></div><div class="p2p-stat"><div class="kicker">Peers</div><strong id="p2pPeerCount">0</strong><p class="small muted">Ephemeral peer connections; no identity verification.</p></div><div class="p2p-stat"><div class="kicker">Transport model</div><strong>WebRTC direct-first</strong><p class="small muted">TURN is an explicit fallback when NAT/firewall traversal prevents direct connections.</p></div></div></section>
<section class="section"><h2>Join a peer room</h2><div class="formgrid">
<div class="field"><label for="p2pAlias">Display alias ${tip('alias','display alias','A label announced to peers. It is not proof of a real person or organization and should not contain sensitive information.')}</label><input id="p2pAlias" maxlength="80" placeholder="e.g., County health planner"></div>
<div class="field"><label for="p2pRole">Disciplinary role ${tip('role','disciplinary role','A collaboration perspective such as public health, transport, broadband, school health or family/caregiver. It changes context only; it grants no technical permissions.')}</label><select id="p2pRole">${['Family / caregiver','Community health worker','Public health','Primary care / clinic','Nursing','EMS / emergency management','Behavioral health','Pharmacy','Maternal / child health','School / education','University / research','Transportation','Housing','Food systems','Water / sanitation','Energy / utilities','Broadband / IT','Benefits / finance','Nonprofit / community organization','Business / employer','Corporation / health system','Municipality / county','State / public institution'].map(x=>`<option>${x}</option>`).join('')}</select></div>
<div class="field"><label for="p2pOrg">Organization label</label><input id="p2pOrg" maxlength="120" placeholder="Optional; self-asserted"></div>
<div class="field"><label for="p2pRoom">Room ID ${tip('room','room ID','A shared namespace used for peer discovery. Anyone who knows a public room ID may attempt to join. For intended groups, use a non-obvious room ID plus a shared password.')}</label><input id="p2pRoom" value="${esc(localStorage.getItem('txh-p2p-room')||'texas-health-working-room')}"></div>
<div class="field"><label for="p2pStrategy">Discovery strategy ${tip('strategy','discovery strategy','The network used only to help browsers find one another and exchange WebRTC session information. Workspace traffic then flows peer-to-peer over WebRTC. Nostr is the default; MQTT, BitTorrent and IPFS are alternatives.')}</label><select id="p2pStrategy"><option value="nostr">Nostr — default</option><option value="mqtt">MQTT</option><option value="torrent">BitTorrent</option><option value="ipfs">IPFS</option></select></div>
<div class="field"><label for="p2pPassword">Shared room password ${tip('password','room password','Passed to Trystero so session-description encryption uses a key derived from this shared secret instead of only the app ID and room name. It is not individual identity or role-based authorization. The app keeps it in sessionStorage, not persistent localStorage.')}</label><input id="p2pPassword" type="password" autocomplete="off" placeholder="Optional but recommended for intended groups"></div>
</div><div class="btnrow" style="margin-top:.7rem"><button class="btn primary" id="p2pJoin">Join room</button><button class="btn" id="p2pSend">Send current snapshot</button><button class="btn" id="p2pLeave">Leave room</button><label class="btn"><input type="checkbox" id="publicLobbyToggle" checked> public commons auto-join</label></div>
<div class="notice"><strong>TURN is not hidden infrastructure.</strong> Direct WebRTC cannot traverse every NAT/firewall. This bundle ships with no TURN credentials. Administrators can add explicit <code>turnConfig</code> entries in <code>config.js</code>; TURN is used only when configured and needed. ${tip('peer','peer networking','WebRTC normally attempts direct encrypted data-channel connections between browsers. A TURN server relays traffic only when direct connectivity fails. Discovery relays and TURN have different roles.')}</div>
<div id="p2pPeerList" class="peer-list"></div></section>
<section class="section"><div class="suite-toolbar"><div class="field"><label>Active workspace</label><select id="wsSelect"></select></div><button class="btn" id="refreshWorkspace">Refresh</button></div>
<details class="details" open><summary>Create multidisciplinary workspace</summary><div><div class="formgrid"><div class="field"><label>Title</label><input id="wsTitle" placeholder="e.g., Rural maternal transport + broadband access"></div><div class="field"><label>Texas geography</label><input id="wsGeo" placeholder="county, region, city or service area"></div><div class="field"><label>Objective</label><textarea id="wsObjective" placeholder="State a measurable access problem without including patient-identifying information."></textarea></div></div><p class="kicker">Disciplines</p><div class="discipline-tags">${ADV_DISCIPLINES.map((d,i)=>`<label><input type="checkbox" data-discipline value="${esc(d)}" ${i<5?'checked':''}> ${esc(d)}</label>`).join('')}</div><div class="btnrow" style="margin-top:.7rem"><button class="btn primary" id="createWorkspace">Create workspace</button></div></div></details><div id="workspaceSummary"></div></section>
<section class="section"><h2>Shared projects</h2><div class="formgrid"><div class="field"><label>Project title</label><input id="sharedProjectTitle" placeholder="e.g., Library telehealth access point"></div><div class="field"><label>Lead entity</label><input id="sharedProjectLead" placeholder="clinic, school, county, business, family coalition…"></div><div class="field"><label>Cross-domain dependencies</label><input id="sharedProjectDeps" placeholder="broadband, mobility, energy, accessibility…"></div><div class="field"><label>Outcome measure</label><input id="sharedProjectMetric" placeholder="e.g., travel hours avoided / completed referrals"></div></div><div class="btnrow" style="margin-top:.6rem"><button class="btn primary" id="addSharedProject">Add shared project</button></div><div id="sharedProjectList"></div></section>
<section class="section"><h2>Shared task board</h2><div class="formgrid"><div class="field"><label>Task</label><input id="taskTitle"></div><div class="field"><label>Lead discipline</label><select id="taskDiscipline">${ADV_DISCIPLINES.map(d=>`<option>${esc(d)}</option>`).join('')}</select></div><div class="field"><label>Owner / role</label><input id="taskOwner"></div><div class="field"><label>Due</label><input id="taskDue" type="date"></div><div class="field"><label>Evidence / dependency note</label><input id="taskNote"></div></div><div class="btnrow" style="margin-top:.6rem"><button class="btn primary" id="addTask">Add task</button></div><div id="taskBoard" class="board"></div></section>
<section class="section"><div class="suite-grid"><article class="card"><h3>Decision log</h3><div class="field"><label>Decision / candidate choice</label><textarea id="decisionText"></textarea></div><div class="field"><label>Rationale + evidence IDs/URLs</label><textarea id="decisionWhy"></textarea></div><button class="btn" id="addDecision">Record decision</button><div id="decisionList"></div></article><article class="card"><h3>Team discussion</h3><div class="field"><label>Name / role</label><input id="commentAuthor" placeholder="e.g., county planner"></div><div class="field"><label>Comment</label><textarea id="commentText"></textarea></div><button class="btn" id="addComment">Add comment</button><div id="commentList"></div></article></div></section>
<section class="section"><details class="details"><summary>Conflict review</summary><div><p>Records are merged by stable IDs and <code>updatedAt</code>. If equal timestamps carry different content, the app keeps a deterministic winner and stores both versions for human review instead of silently pretending there was no conflict.</p><div id="syncConflictList"></div></div></details></section>
<section class="section"><details class="details"><summary>Legacy / optional Node synchronization adapter</summary><div><p>This centralized adapter remains for backward compatibility, persistence experiments or networks where P2P is unsuitable. It is not required for Trystero/WebRTC collaboration and is not a clinical/HIPAA system.</p><div class="formgrid"><div class="field"><label>Legacy server URL</label><input id="syncServer" placeholder="https://your-host.example" value="${esc((location.protocol==='http:'||location.protocol==='https:')?location.origin:'')}"></div><div class="field"><label>Legacy room ID</label><input id="syncRoom" value="${esc(localStorage.getItem('txh-room')||'')}"></div><div class="field"><label>Legacy access key</label><input id="syncKey" type="password" autocomplete="off"></div></div><div class="btnrow" style="margin-top:.6rem"><button class="btn" id="generateRoomCreds">Generate room + key</button><button class="btn" id="createRemoteRoom">Create legacy room</button><button class="btn" id="syncNow">Sync once</button><button class="btn" id="autoSync">Start legacy polling</button><button class="btn" id="stopSync">Stop</button></div><p id="syncStatus" class="small muted">Legacy adapter idle.</p></div></details></section>`}

const GUIDES=[
{title:'Texas health collaboration operating model',summary:'How families, clinics, schools, public agencies, businesses and infrastructure partners can work on the same access problem without turning the workspace into a clinical record.',one:`Treat the OS as a shared planning table. Start with a concrete access barrier—travel, coverage, workforce, broadband, heat, language or continuity—then separate <strong>personal care</strong> from <strong>system coordination</strong>. Personal health data stays local; shared rooms contain tasks, evidence, decisions and projects.`,steps:list(['Define the geography and affected population without identifying individuals.','Invite the smallest set of disciplines needed to understand the barrier.','Create one measurable objective and baseline.','Attach evidence with source/date/limitations.','Assign task ownership and review outcomes before scaling.']),advanced:`Use a common operating picture: verified facts, reported-but-unverified observations, modeled scenarios and unknowns. Cross-domain teams should explicitly record dependencies—for example telehealth ↔ broadband ↔ power ↔ privacy ↔ clinician availability ↔ transportation fallback.`,expert:`For institutional deployment, add organization-grade identity, authorization, retention policies, legal/privacy review, incident handling and signed provenance. Trystero peer IDs are transport identifiers only and should never be treated as proof that someone represents a hospital, school, company or government.`},
{title:'Trystero 0.25.3 + WebRTC',summary:'How decentralized discovery differs from the direct data path, and where TURN fits.',one:`Trystero helps browsers <em>find</em> peers through a discovery strategy, then uses WebRTC data channels for room traffic. This bundle pins <strong>0.25.3</strong> and uses the 0.25.x action-object API. Nostr is default; MQTT, BitTorrent and IPFS are selectable.`,steps:list(['Choose a room ID and discovery strategy.','Use a shared password for intended groups.','Join from two devices/browsers.','Watch the peer list and send a workspace snapshot.','If a specific network pairing fails, test another network before configuring TURN.']),advanced:`The app creates Trystero actions for presence and workspace snapshots. Existing peers send snapshots when a new peer joins, so the newcomer can reconstruct projects/tasks/comments/decisions/evidence without a central application database. Same-device BroadcastChannel uses the same merge model when internet discovery is unavailable.`,expert:`Direct WebRTC connectivity depends on ICE/NAT traversal. Trystero documents TURN as a relay fallback for pairings that cannot establish a direct connection. Configure <code>turnConfig</code> explicitly in <code>config.js</code>; the bundle does not ship third-party TURN credentials. Shared passwords strengthen session-description encryption but are not identity federation or fine-grained authorization.`},
{title:'Texas broadband + health access status',summary:'Why broadband deployment belongs inside a health-access OS, with current Texas program facts.',one:`Telehealth access is constrained by coverage, affordability, devices, privacy, power and clinical appropriateness. Texas’s BEAD Final Proposal was approved <strong>December 4, 2025</strong>. The state reports 22 selected applicants serving more than 240,000 broadband-serviceable locations and more than 2,700 community anchor institutions.`,steps:list(['Check whether a proposed clinic/library/school telehealth site is in an awarded deployment area.','Do not equate a broadband award with a currently usable connection—track build/activation status separately.','Pair connectivity planning with private space, devices, accessibility and technical support.','Keep an in-person/phone/transport fallback for care that cannot be delivered remotely.']),advanced:`Texas reports $1.2B in federal BEAD grant funds plus $177M state match in the approved proposal. Separately, HHSC’s SFY 2026 Pediatric Tele-Connectivity Resource Program was designed to connect rural hospitals and rural health clinics with pediatric specialists/subspecialists or eligible higher-education partners. These programs address different layers: broadband infrastructure versus health-service connectivity.`,expert:`A production map should join BSL/CAI award data to health facilities, HPSA/MUA-P layers, road travel time, power resilience and service-line availability using dated provenance. Avoid claiming “telehealth access” from bandwidth alone; model end-to-end service readiness and the date at which each dependency is operational.${sourceCard('tx-bdo-bead')}${sourceCard('hhsc-rural-peds-teleconnect')}`},
{title:'Mapping health-access challenges',summary:'How to avoid turning a pretty map into a misleading care-desert claim.',one:`A facility point on a map does not prove that care is available. Maps must distinguish facility existence from service type, hours, appointment capacity, affordability, language/accessibility and actual travel time.`,steps:list(['Choose the decision first: referral, transport, workforce, broadband, disaster continuity or investment.','Use authoritative facility and shortage-designation layers.','Add road/travel-time and accessibility constraints.','Record each layer’s date and geography.','Label modeled travel/capacity results as models—not measured facts.']),advanced:`Rural Texas requires attention to large catchments, cross-county travel, seasonal hazards and sparse provider networks. Hospital-level mapping can also be misleading when service lines change. Use separate layers for hospital presence, emergency services, maternity, behavioral health, pharmacy and telehealth readiness where reliable data exist.`,expert:`For geospatial production work, maintain source CRS, license, vintage, join keys, suppressed cells and uncertainty metadata. Prefer reproducible transformations and preserve raw-source identifiers. Do not map household-level health vulnerabilities into public peer rooms; aggregate or de-identify before sharing.`},
{title:'Multidisciplinary project design',summary:'A repeatable way to turn a Texas health-access problem into a governed cross-domain project.',one:`Good projects start with a measurable barrier and an explicit population/geography—not a favored technology. Compare several interventions before deciding.`,steps:list(['Problem: state the friction and baseline.','Partners: include health plus relevant mobility, broadband, school, utility, housing or community actors.','Options: compare at least two interventions.','Evidence: attach sources and uncertainty.','Operations: define staffing, maintenance, privacy, accessibility and failure modes.','Metrics: distinguish outputs from actual outcomes.']),advanced:`Use a dependency register, risk register and decision log. Example: a library telehealth hub may depend on broadband, private rooms, accessible transport, device support, clinical partners, scheduling workflows and sustainable operating funds. A mobile clinic may solve travel but introduce staffing, routing, maintenance and referral-continuity constraints.`,expert:`Institutional programs should add data governance, procurement, security threat modeling, legal authority, accessibility testing, equity analysis that does not rank human worth, and stop/modify criteria if outcomes diverge from assumptions. Use the evidence grade and decision log so future teams can reconstruct why a choice was made.`},
{title:'WebLLM local planning architecture',summary:'How local AI is isolated from the interface and what happens when it cannot run.',one:`WebLLM can run supported models in the browser with WebGPU. This bundle uses a <strong>dedicated Web Worker</strong> so heavy inference does not block the UI. Model code/artifacts must be obtained online on first use and may be cached locally.`,steps:list(['Check WebGPU support.','Discover supported models.','Choose a model appropriate for device memory.','Load it in the dedicated worker.','Use de-identified planning prompts and verify factual claims against sources.']),advanced:`The adapter uses <code>CreateWebWorkerMLCEngine</code> and a worker-side <code>WebWorkerMLCEngineHandler</code>. The app requests IndexedDB model caching. If WebGPU, the model or the CDN is unavailable, the UI falls back to a deterministic rule-based planning scaffold rather than fabricating an AI response.`,expert:`For managed deployments, pin WebLLM/model versions, review model licenses, implement resource budgets, capture model/version in generated-plan metadata and separate retrieval/evidence from generation. A local model does not automatically make outputs correct, clinically safe or suitable for eligibility decisions.${sourceCard('webllm-worker-docs')}`},
{title:'PWA + offline architecture',summary:'What remains available offline, what does not, and how updates are handled.',one:`The hosted app is installable as a PWA. The service worker precaches the local shell, guides, source registry and collaboration code. IndexedDB holds local records. Live websites, decentralized discovery and first-time AI model downloads still require connectivity.`,steps:list(['Serve through HTTPS or localhost.','Install the PWA after the manifest/service worker are active.','Test once online, then test critical local tools offline.','Export JSON backups periodically.','Check freshness labels before using cached resource information.']),advanced:`The service worker uses versioned static/runtime caches and excludes API collaboration state. Cross-origin Trystero/WebLLM assets are not falsely advertised as bundled offline resources. Same-device BroadcastChannel can still coordinate tabs without the network.`,expert:`For high-assurance deployments, pin and self-host audited third-party modules, add Subresource Integrity where deployment architecture supports it, stage service-worker updates, test schema migrations and publish cache/version provenance. Opening <code>index.html</code> through <code>file://</code> never activates the service worker.`},
{title:'Evidence + provenance',summary:'How to prevent source drift and “current” claims from quietly becoming stale.',one:`Every important planning claim should answer: who published it, what dataset/document it came from, what geography/time it represents, when it was retrieved, and what its limitations are.`,steps:list(['Prefer official measured/administrative sources for operational facts.','Store source URL, date, geography and evidence grade.','Separate FACT, INFERENCE, MODEL, SCENARIO and HYPOTHESIS.','Mark cached/stale content visibly.','Re-verify before funding, eligibility, clinical or emergency decisions.']),advanced:`Evidence grades A–F describe source/evidence type, not moral value. A strong source can still be too old, geographically mismatched or unsuitable for a particular inference. Preserve the exact input data and assumptions used by calculators and scenario models.`,expert:`For collaborative provenance, add content hashes, source snapshots where licensing allows, signed institutional attestations where identity matters and a reproducible transformation log. SHA-256 can show that bytes are unchanged; it does not establish authorship or creation time by itself.`}
];

function renderGuides(){return `${renderRouteHeader('Simplified Advanced Guides','Progress from a one-minute explanation to actions, advanced reasoning and implementation detail without forcing every user through expert material.')}
<section class="section"><div class="formgrid"><div class="field"><label for="guideSearch">Filter guides</label><input id="guideSearch" placeholder="Try: WebRTC, broadband, mapping, evidence…"></div></div><div class="btnrow" style="margin-top:.6rem"><button class="btn" id="expandGuides">Expand all</button><button class="btn" id="collapseGuides">Collapse all</button></div></section>
<section class="section"><div class="guide-list" id="guideList">${GUIDES.map((g,i)=>`<details class="guide" data-guide="${esc((g.title+' '+g.summary).toLowerCase())}" ${i===0?'open':''}><summary>${esc(g.title)} <span class="small muted">— ${esc(g.summary)}</span></summary><div class="guide-body"><div class="guide-levels"><article class="guide-level"><div class="level-badge">1 minute</div><h4>Understand it</h4><p>${g.one}</p></article><article class="guide-level"><div class="level-badge">Actionable</div><h4>Do this next</h4>${g.steps}</article><article class="guide-level"><div class="level-badge">Advanced</div><h4>See the system</h4><p>${g.advanced}</p></article><article class="guide-level"><div class="level-badge">Expert / implementation</div><h4>Build it correctly</h4><p>${g.expert}</p></article></div></div></details>`).join('')}</div></section>`}

function factCard(type,title,text,sourceId){return `<article class="fact-card"><div class="fact-type">${esc(type)}</div><h3>${esc(title)}</h3><p>${text}</p>${sourceId?sourceCard(sourceId):''}</article>`}
function renderFieldGuide(){return `${renderRouteHeader('Texas Health Access Field Guide — 2026','Concrete, source-backed operating information for health access, workforce, transport, behavioral health, maternal health, broadband and cross-domain planning. Recheck official sources before operational decisions.')}
<section class="section"><div class="notice good"><strong>Verification date:</strong> 2026-09-28. “Current” here means current to that verification date; downstream program availability and individual eligibility can change.</div><div class="facts-grid">
${factCard('FACT','Nonemergency Medicaid transportation',`Texas HHSC states that eligible Medicaid beneficiaries and certain other program participants without another means of transportation can receive rides to covered services. HHSC says routine requests should generally be made at least <strong>two workdays</strong> before an appointment, or <strong>five days</strong> when traveling outside the county; same-day rides may be approved in specified circumstances.`,`txhhs-transport`)}
${factCard('FACT','Official benefits application path',`Texas HHSC directs people applying for Medicaid/CHIP and other benefits to <strong>Your Texas Benefits</strong>. The platform can support application preparation, but only the official eligibility process can determine whether a person qualifies.`,`ytb`)}
${factCard('FACT','Health centers for uninsured and underinsured people',`HRSA states that Health Center Program clinics provide primary medical and dental care regardless of insurance status and adjust fees using a sliding scale based on ability to pay. Individual clinic services, hours and appointment availability still require verification.`,`hrsa`)}
${factCard('FACT','Aging and disability navigation',`Texas HHSC's service finder locates Area Agencies on Aging, Aging and Disability Resource Centers, Local Mental Health Authorities and Local IDD Authorities by county or ZIP. HHSC also lists <strong>855-937-2372</strong> for help identifying aging/disability services.`,`hhsc-services-directory`)}
${factCard('FACT','Texas Medicare counseling',`Texas HHSC lists a free Medicare help line at <strong>800-252-9240</strong> and describes HICAP as a source of benefits counseling for Medicare enrollment, options and cost-assistance questions.`,`tx-hicap`)}
${factCard('FACT','Federal medical-bill protections',`CMS explains No Surprises Act protections and says providers usually must give uninsured/self-pay patients a good-faith estimate for scheduled care. A federal patient-provider dispute process may be available when an eligible bill is at least $400 above the estimate; CMS lists important exceptions, including many ground-ambulance bills.`,`cms-bill-rights`)}
${factCard('FACT','Early Childhood Intervention pathway',`Texas HHS describes Early Childhood Intervention as serving children from birth up to 36 months with qualifying developmental delay, disability or certain diagnosed conditions. The OS links the official program instead of attempting developmental diagnosis.`,`hhsc-disability`)}
${factCard('FACT','Behavioral-health crisis access',`Texas HHSC points people to <strong>988</strong>, 2-1-1 Texas and 24/7 Local Mental Health/Behavioral Health Authority crisis lines. Immediate threats to life or safety should use emergency services.`,`hhsc-crisis`)}
${factCard('FACT','Shortage designations',`Texas DSHS and HRSA use HPSA/MUA-P designations to identify shortages in primary care, dental and mental-health services. DSHS notes that more than 30 federal/state programs use shortage designation in eligibility or targeting.`,`dshs-hpsa`)}
${factCard('FACT','Community health workers / promotores',`Texas DSHS defines CHWs as community-based connectors to healthcare and social services. Paid CHWs require DSHS certification; current pathways include approved training or qualifying experience. Updated core competencies became effective in 2026.`,`dshs-chw-current`)}
${factCard('FACT','Maternal-health data',`Texas DSHS Health Data publishes maternal-health dashboards covering topics such as maternal mortality, pregnancy planning, maternal mental health and physical-health factors, with documented underlying data sources and limitations.`,`tx-health-data`)}
${factCard('FACT','Rural pediatric tele-connectivity',`HHSC's SFY 2026 program was designed to connect rural hospitals and rural health clinics with pediatric specialists/subspecialists or eligible higher-education partners. This is a health-service connectivity program, not a substitute for general broadband deployment.`,`hhsc-rural-peds-teleconnect`)}
${factCard('FACT','Texas BEAD status',`Texas's BEAD Final Proposal was approved <strong>December 4, 2025</strong>. The Broadband Development Office reports 22 selected applicants, more than 240,000 broadband-serviceable locations and more than 2,700 community anchor institutions, with $1.2B federal grant funds and $177M state match. An award does not necessarily mean a location is already activated.`,`tx-bdo-bead`)}
${factCard('FACT','2026 hospital price-transparency data',`CMS's 2026 rules added median, 10th- and 90th-percentile allowed amounts plus counts for certain percentage/algorithm-based negotiated charges. CMS began enforcement of the new/revised 2026 requirements on April 1, 2026. Published amounts still are not a guaranteed individual bill.`,`cms-price`)}
${factCard('FACT','School health',`Texas DSHS publishes school-year immunization materials and related school-health resources. The OS links current hubs instead of freezing a permanent schedule into offline code.`,`dshs-school`)}
${factCard('FACT','Air and drinking water',`TCEQ provides official Texas air-quality and public drinking-water information. These are environmental context layers; they do not establish an individual's medical diagnosis.`,`tceq-air`)}
${factCard('SYSTEM','Health ↔ mobility',`Travel time, accessible vehicles, backup rides and appointment timing can determine whether a referral is practically usable. Pair clinic directories with transport planning rather than treating “nearest facility” as “accessible care.”`,`txdot-transit`)}
${factCard('SYSTEM','Health ↔ power ↔ broadband',`Telehealth, medication refrigeration, powered medical devices, cooling and communications can fail together during outages. Continuity plans should identify primary and backup power, communication and transportation options.`,`cdc-heat-med`)}
</div></section>
<section class="section"><h2>Cross-institution operating patterns</h2><div class="grid">${[
['Family + clinic + transport','Use for missed appointments, rural travel, accessibility needs and follow-up ownership.'],['School + public health + family','Use for school-health education, referrals, immunization-process navigation and chronic-condition coordination without exposing student health data in public workspaces.'],['County + hospital + broadband + library','Use for telehealth hubs, connectivity gaps and accessible community anchor sites.'],['Health system + utility + emergency management','Use for powered medical-device continuity, cooling, evacuation and outage communications.'],['University + public agency + nonprofit','Use for evidence review, evaluation design, workforce pipelines and community-engaged pilots.'],['Employer + occupational health + public health','Use for heat planning, emergency response, worker access and referral pathways while preserving employment/privacy protections.']
].map(([a,b])=>`<article class="card"><h3>${a}</h3><p>${b}</p></article>`).join('')}</div></section>`}

function installSplash(){
  if(document.getElementById('txhSplash'))return;
  document.body.insertAdjacentHTML('afterbegin',`<div class="splash" id="txhSplash" role="dialog" aria-modal="true" aria-labelledby="splashTitle"><div class="splash-card"><div class="splash-rings" aria-hidden="true"><span class="splash-ring" style="--i:0"></span><span class="splash-ring" style="--i:1"></span><span class="splash-ring" style="--i:2"></span><span class="splash-core">TX</span></div><div class="eyebrow">Texas Health Access Navigator OS v4</div><h1 id="splashTitle">Connect evidence. Coordinate disciplines. Improve access.</h1><p>Local-first health navigation plus decentralized project collaboration across families, care teams, schools, institutions, businesses, infrastructure partners and public agencies.</p><div class="splash-track" aria-hidden="true"><span id="splashProgress"></span></div><div class="splash-steps"><div class="splash-step" id="splashConnectivity">Connectivity · checking</div><div class="splash-step" id="splashEvidence">Evidence · loading</div><div class="splash-step" id="splashCollaboration">Collaboration · preparing</div></div><div class="splash-actions"><button class="btn primary" id="splashEnter">Enter workspace now</button><button class="btn" id="splashReduce">Reduce motion</button></div><p class="privacy-note">The default public commons uses Nostr discovery and WebRTC presence with a random peer ID plus any alias/role you choose. Identities are not verified. Personal health records are never automatically published to the public room.</p></div></div>`);
  const splash=document.getElementById('txhSplash'),bar=document.getElementById('splashProgress');
  const reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
  const set=(pct,id,text)=>{bar.style.width=pct+'%';const e=document.getElementById(id);e.classList.add('ready');e.textContent=text};
  if(reduced){set(100,'splashConnectivity',navigator.onLine?'Connectivity · online':'Connectivity · offline');document.getElementById('splashEvidence').classList.add('ready');document.getElementById('splashEvidence').textContent='Evidence · bundled';document.getElementById('splashCollaboration').classList.add('ready');document.getElementById('splashCollaboration').textContent='Collaboration · ready'}else{setTimeout(()=>set(34,'splashConnectivity',navigator.onLine?'Connectivity · online':'Connectivity · offline'),250);setTimeout(()=>set(68,'splashEvidence','Evidence · bundled + dated'),800);setTimeout(()=>set(100,'splashCollaboration','Collaboration · local-first ready'),1450)}
  const close=()=>{splash.classList.add('leave');setTimeout(()=>splash.remove(),reduced?0:360)};
  document.getElementById('splashEnter').onclick=close;
  document.getElementById('splashReduce').onclick=()=>{document.documentElement.style.scrollBehavior='auto';document.querySelectorAll('.splash-ring').forEach(x=>x.style.animation='none');bar.style.transition='none';set(100,'splashConnectivity',navigator.onLine?'Connectivity · online':'Connectivity · offline');document.getElementById('splashEvidence').classList.add('ready');document.getElementById('splashEvidence').textContent='Evidence · bundled';document.getElementById('splashCollaboration').classList.add('ready');document.getElementById('splashCollaboration').textContent='Collaboration · ready'};
}

function bindTooltips(){document.querySelectorAll('.tip-btn').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const w=b.closest('.tip-wrap'),open=w.dataset.open==='true';document.querySelectorAll('.tip-wrap[data-open="true"]').forEach(x=>x.dataset.open='false');w.dataset.open=String(!open);b.setAttribute('aria-expanded',String(!open))});b.addEventListener('keydown',e=>{if(e.key==='Escape'){b.closest('.tip-wrap').dataset.open='false';b.setAttribute('aria-expanded','false');b.focus()}})});}

async function renderPeerProjects(){const el=document.getElementById('sharedProjectList');if(!el)return;const wid=localStorage.getItem('txh-active-workspace')||'';const rows=(await idbAll('projects')).filter(x=>x.workspaceId===wid);el.innerHTML=rows.length?`<div class="grid" style="margin-top:.8rem">${rows.map(x=>`<article class="card"><h3>${esc(x.title||x.intervention||'Shared project')}</h3><p><strong>Lead:</strong> ${esc(x.lead||x.partners||'unassigned')}</p><p><strong>Dependencies:</strong> ${esc(x.dependencies||'not entered')}</p><p><strong>Outcome:</strong> ${esc(x.metric||x.metrics||'not entered')}</p></article>`).join('')}</div>`:'<p class="muted">No shared projects in this workspace yet.</p>'}
async function addSharedProject(){const wid=localStorage.getItem('txh-active-workspace')||'',title=document.getElementById('sharedProjectTitle')?.value.trim();if(!wid)return alert('Create or choose a workspace first.');if(!title)return alert('Enter a project title.');const item={id:`project-${Date.now().toString(36)}-${crypto.getRandomValues(new Uint32Array(1))[0].toString(36)}`,workspaceId:wid,title,lead:document.getElementById('sharedProjectLead').value.trim(),dependencies:document.getElementById('sharedProjectDeps').value.trim(),metric:document.getElementById('sharedProjectMetric').value.trim(),status:'concept',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};await idbPut('projects',item);window.TXHCollab?.announce?.({type:'workspace-change',workspaceId:wid});document.getElementById('sharedProjectTitle').value='';await renderPeerProjects()}
async function renderConflicts(){const el=document.getElementById('syncConflictList');if(!el)return;let rows=[];try{rows=(await idbAll('syncConflicts')).slice(-10).reverse()}catch{}el.innerHTML=rows.length?rows.map(x=>`<div class="callout"><span>⚠</span><div><strong>${esc(x.store)} / ${esc(x.recordId)}</strong><div class="small">Conflicting equal-timestamp versions received from ${esc(x.peerId||'peer')} at ${esc(x.createdAt||'')}</div><div class="small muted">Both versions remain in this conflict record for manual review.</div></div></div>`).join(''):'<p class="muted">No recorded synchronization conflicts.</p>'}
function updateP2PUI(detail){const stateEl=document.getElementById('p2pState'),msg=document.getElementById('p2pMessage');if(stateEl&&detail){stateEl.textContent=detail.state||'status';msg.textContent=detail.message||''}const st=window.TXHP2P?.status?.();if(st){const c=document.getElementById('p2pPeerCount');if(c)c.textContent=String(st.peerCount);const listEl=document.getElementById('p2pPeerList');if(listEl){const peers=st.peers.filter(p=>p.channel!=='public');listEl.innerHTML=peers.length?`<h3>Connected/recent workspace peers</h3>${peers.map(p=>`<div class="peer-row"><span class="peer-avatar" aria-hidden="true">${esc((p.alias||'?').slice(0,1).toUpperCase())}</span><div><strong>${esc(p.alias||'Unidentified peer')}</strong><div class="small muted">${esc(p.role||'role not shared')}${p.organization?' · '+esc(p.organization):''}</div></div><span class="pill">${esc(p.channel||'peer')} · unverified</span></div>`).join('')}</div>`:''}}}
function installP2PEvents(){if(window.__txhP2PEvents)return;window.__txhP2PEvents=true;window.addEventListener('txh:p2p-status',e=>updateP2PUI(e.detail));window.addEventListener('txh:p2p-peers',()=>updateP2PUI());window.addEventListener('txh:p2p-public',e=>{const el=document.getElementById('publicLobbyStatus');if(el)el.textContent=e.detail?.message||e.detail?.state||'public lobby'});window.addEventListener('txh:p2p-merged',()=>{if(state.route==='collaboration'){document.getElementById('refreshWorkspace')?.click();renderPeerProjects();renderConflicts()}})}
async function bindP2P(){
  bindTooltips();installP2PEvents();
  const $=id=>document.getElementById(id);if(!$('p2pJoin'))return;
  $('p2pAlias').value=localStorage.getItem('txh-peer-alias')||'Texas participant';$('p2pRole').value=localStorage.getItem('txh-peer-role')||'Family / caregiver';$('p2pOrg').value=localStorage.getItem('txh-peer-org')||'';$('p2pStrategy').value=localStorage.getItem('txh-p2p-strategy')||'nostr';$('p2pPassword').value=sessionStorage.getItem('txh-p2p-password')||'';$('publicLobbyToggle').checked=localStorage.getItem('txh-disable-public-lobby')!=='true';
  $('p2pJoin').onclick=async()=>{const opts={roomId:$('p2pRoom').value.trim(),strategy:$('p2pStrategy').value,password:$('p2pPassword').value,alias:$('p2pAlias').value.trim(),role:$('p2pRole').value,organization:$('p2pOrg').value.trim()};try{updateP2PUI({state:'joining',message:'Joining same-device room and decentralized discovery…'});await window.TXHP2P.joinWorkspace(opts);updateP2PUI(window.TXHP2P.status())}catch(e){updateP2PUI({state:'error',message:e.message})}};
  $('p2pSend').onclick=()=>window.TXHP2P.sendSnapshot().catch(e=>updateP2PUI({state:'error',message:e.message}));$('p2pLeave').onclick=()=>window.TXHP2P.leaveWorkspace();$('publicLobbyToggle').onchange=e=>window.TXHP2P.publicEnabled(e.target.checked);$('addSharedProject').onclick=addSharedProject;
  await renderPeerProjects();await renderConflicts();updateP2PUI();
}
function bindGuides(){bindTooltips();const q=document.getElementById('guideSearch'),listEl=document.getElementById('guideList');if(!q||!listEl)return;q.oninput=()=>{const v=q.value.toLowerCase();listEl.querySelectorAll('.guide').forEach(g=>g.hidden=!g.dataset.guide.includes(v))};document.getElementById('expandGuides').onclick=()=>listEl.querySelectorAll('.guide:not([hidden])').forEach(g=>g.open=true);document.getElementById('collapseGuides').onclick=()=>listEl.querySelectorAll('.guide').forEach(g=>g.open=false)}

const collabRoute=ROUTES.find(x=>x.id==='collaboration');if(collabRoute){collabRoute.render=renderP2PCollab;collabRoute.label='Peer Collaboration';collabRoute.keywords+=' Trystero WebRTC Nostr MQTT BitTorrent IPFS TURN peer snapshot'}
const extra=[{id:'health-field-guide',label:'Texas Health Field Guide',group:'Texas Intelligence',keywords:'actual facts Texas Medicaid transport crisis CHW maternal rural telehealth BEAD broadband price transparency',render:renderFieldGuide},{id:'advanced-guides',label:'Simplified Advanced Guides',group:'Advanced',keywords:'guides Trystero WebRTC broadband mapping multidisciplinary WebLLM PWA offline evidence provenance',render:renderGuides}];for(const r of extra)if(!ROUTES.some(x=>x.id===r.id))ROUTES.push(r);

const priorBind=bindRoute;bindRoute=function(id){priorBind(id);bindTooltips();if(id==='collaboration')bindP2P();if(id==='advanced-guides')bindGuides()};

/* Every local collaboration mutation already calls TXHCollab.announce; mirror those events into the active P2P room. */
if(window.TXHCollab&&!window.TXHCollab.__p2pWrapped){const old=window.TXHCollab.announce.bind(window.TXHCollab);window.TXHCollab.announce=detail=>{old(detail);window.TXHP2P?.handleLocalChange?.(detail)};window.TXHCollab.__p2pWrapped=true}

installSplash();installP2PEvents();
window.addEventListener('load',()=>window.TXHP2P?.joinPublicLobby?.());
})();
